name: ISO
'on':
  workflow_dispatch:

jobs:
  iso:
    name: 'Build ISO'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    container:
      image: archlinux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged
    steps:
      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV
      - name: Install dependencies
        run: |
          curl https://gist.githubusercontent.com/flyingcakes85/cb447a6e48cea1d281387356b7471584/raw/daed6e4e6a37d0e620360be717e4ff5b3230a8e5/enos.txt > /etc/pacman.d/endeavouros-mirrorlist
          curl https://gist.githubusercontent.com/flyingcakes85/06efa181e0bafd51f0abcbe90dc7be63/raw/80968d6a320a288835fafe95c673193b3cc68b27/pacman-eos >> /etc/pacman.conf
          pacman-key --init
          pacman-key --keyserver keyserver.ubuntu.com -r 003DB8B0CB23504F
          pacman-key --lsign 003DB8B0CB23504F
          pacman -Syyu archiso mkinitcpio-archiso git squashfs-tools --needed --noconfirm
      - name: Build
        run: |
          git clone https://github.com/endeavouros-team/EndeavourOS-ISO.git
          cd "EndeavourOS-ISO"
          ./fix_permissions.sh
          ./mkarchiso "." 2>&1 | tee "eosiso.log"
      - name: Print working dir
        run: pwd
      - uses: actions/upload-artifact@v2
        with:
          name: EndeavourOS ${{ env.DATE }}
          path: out/*
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.DATE }}
          prerelease: true
          title: "EndeavourOS"
          files: |
            out/*
